name: poc-security-check
version: git
summary: POC for keyboard events.
description: >
  Start test if listening for keys:
    $ pockeyevents

confinement: devmode

parts:
  pockeyevents:
    plugin: nodejs
    source: .

apps:
  pockeyevents:
    command: pockeyevents
